POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRFU1RJIiwiaWQiOiI2MThlMjA2MTdhZTQ2YThkZWFiMTljM2IiLCJpYXQiOjE2MzY3MDQzNjksImV4cCI6MTYzNjcwNzk2OX0.yX0wdHlNetM-RZG-9DfaY_XYsOnsJ2FOqvMGqPwWWJs

{
  "title": "testi",
  "author": "kirjoittaja",
  "url": "https://testi.com",
  "likes": 987234
}